version: '3.9'

services:
  ecommerce-mysql:
    build:
      context: ./docker/mysql
    container_name: ecommerce-mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - ecommerce

  ecommerce-catalog:
    build:
      context: ./catalog
    container_name: ecommerce-catalog
    depends_on:
      - ecommerce-mysql
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=ecommerce-mysql
      - DATABASE_NAME=ecom
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
    networks:
      - ecommerce

  ecommerce-carts:
    build:
      context: ./cart
    container_name: ecommerce-carts
    depends_on:
      - ecommerce-mysql
    restart: always
    ports:
      - 8081:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=ecommerce-mysql
      - DATABASE_NAME=ecom
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
    networks:
      - ecommerce

  ecommerce-checkout:
    build:
      context: ./checkout
    container_name: ecommerce-checkout
    depends_on:
      - ecommerce-mysql
    restart: always
    ports:
      - 8082:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=ecommerce-mysql
      - DATABASE_NAME=ecom
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
    networks:
      - ecommerce

  card-service:
    build:
      context: ./card
    container_name: card-service
    depends_on:
      - ecommerce-mysql
    restart: always
    ports:
      - 8083:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=ecommerce-mysql
      - DATABASE_NAME=ecom
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
    networks:
      - ecommerce

  email-service:
    build:
      context: ./email
    container_name: email-service
    depends_on:
      - ecommerce-mysql
    restart: always
    ports:
      - 8084:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=ecommerce-mysql
      - DATABASE_NAME=ecom
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
    networks:
      - ecommerce

  node:
    build:
      context: ./ecommerce
    container_name: node
    depends_on:
      - ecommerce-catalog
      - ecommerce-mysql
      - ecommerce-carts
      - ecommerce-checkout
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - ecommerce

networks:
  ecommerce:
    name: ecommerce
